In [1]:
import pandas as pd
import numpy as np

In [2]:
a = pd.read_csv("adult_new.csv")

In [3]:
a.head()

,age,workclass,fnlwgt,education,educational-num,marital-status,occupation,relationship,race,gender,capital-gain,capital-loss,hours-per-week,native-country,income
0,28,Local-gov,336951,Assoc-acdm,12,Married-civ-spouse,Protective-serv,Husband,White,Male,0,0,40,United-States,>50K
1,44,Private,160323,Some-college,10,Married-civ-spouse,Machine-op-inspct,Husband,Black,Male,7688,0,40,United-States,>50K
2,63,Self-emp-not-inc,104626,Prof-school,15,Married-civ-spouse,Prof-specialty,Husband,White,Male,3103,0,32,United-States,>50K
3,65,Private,184454,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,6418,0,40,United-States,>50K
4,48,Private,279724,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,3103,0,48,United-States,>50K


In [4]:
a.shape

(27414, 15)

In [5]:
a.isnull().sum()

age                0
workclass          0
fnlwgt             0
education          0
educational-num    0
marital-status     0
occupation         0
relationship       0
race               0
gender             0
capital-gain       0
capital-loss       0
hours-per-week     0
native-country     0
income             0
dtype: int64

In [6]:
a.dtypes

age                 int64
workclass          object
fnlwgt              int64
education          object
educational-num     int64
marital-status     object
occupation         object
relationship       object
race               object
gender             object
capital-gain        int64
capital-loss        int64
hours-per-week      int64
native-country     object
income             object
dtype: object

In [7]:
for i in a.columns:
    print(f"----------\n",a[i].unique())

----------
 [28 44 63 65 48 43 40 34 45 46 36 22 42 41 55 33 59 29 27 31 58 54 37 56
 39 51 50 52 47 24 64 53 35 32 30 68 57 66 49 38 61 73 26 23 25 62 90 60
 67 69 72 85 71 77 70 19 21 74 75 20 81 76 80 88 78 79 84 17 18 82 83 86
 87]
----------
 ['Local-gov' 'Private' 'Self-emp-not-inc' 'State-gov' 'Self-emp-inc' '?'
 'Federal-gov' 'Without-pay' 'Never-worked']
----------
 [336951 160323 104626 ...  84661 310152 257302]
----------
 ['Assoc-acdm' 'Some-college' 'Prof-school' 'HS-grad' 'Masters' 'Doctorate'
 'Bachelors' 'Assoc-voc' '9th' '10th' '7th-8th' '11th' '5th-6th' '1st-4th'
 '12th' 'Preschool']
----------
 [12 10 15  9 14 16 13 11  5  6  4  7  3  2  8  1]
----------
 ['Married-civ-spouse' 'Never-married' 'Divorced' 'Separated'
 'Married-AF-spouse' 'Widowed' 'Married-spouse-absent']
----------
 ['Protective-serv' 'Machine-op-inspct' 'Prof-specialty' 'Exec-managerial'
 'Tech-support' 'Craft-repair' 'Sales' 'Other-service' '?'
 'Transport-moving' 'Adm-clerical' 'Handlers-cleaners' 

In [8]:
a = a.replace("?",np.nan)

In [9]:
a.isnull().sum()

age                   0
workclass          1283
fnlwgt                0
education             0
educational-num       0
marital-status        0
occupation         1288
relationship          0
race                  0
gender                0
capital-gain          0
capital-loss          0
hours-per-week        0
native-country      508
income                0
dtype: int64

In [10]:
for value in ["workclass","occupation","native-country"]:
    a[value].fillna(a[value].mode()[0], inplace=True)

C:\Users\pchor\AppData\Local\Temp\ipykernel_13644\3134475680.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  a[value].fillna(a[value].mode()[0], inplace=True)


In [11]:
a.isnull().sum()

age                0
workclass          0
fnlwgt             0
education          0
educational-num    0
marital-status     0
occupation         0
relationship       0
race               0
gender             0
capital-gain       0
capital-loss       0
hours-per-week     0
native-country     0
income             0
dtype: int64

In [12]:
colname=[]
for x in a.columns:
    if a[x].dtypes=="object":
        colname.append(x)
colname

['workclass',
 'education',
 'marital-status',
 'occupation',
 'relationship',
 'race',
 'gender',
 'native-country',
 'income']

In [13]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

for x in colname:
    a[x] = le.fit_transform(a[x])


    le_name_mapping = dict(zip(le.classes_,le.transform(le.classes_)))
    print("features", x)
    print("mapping", le_name_mapping)

features workclass
mapping {'Federal-gov': 0, 'Local-gov': 1, 'Never-worked': 2, 'Private': 3, 'Self-emp-inc': 4, 'Self-emp-not-inc': 5, 'State-gov': 6, 'Without-pay': 7}
features education
mapping {'10th': 0, '11th': 1, '12th': 2, '1st-4th': 3, '5th-6th': 4, '7th-8th': 5, '9th': 6, 'Assoc-acdm': 7, 'Assoc-voc': 8, 'Bachelors': 9, 'Doctorate': 10, 'HS-grad': 11, 'Masters': 12, 'Preschool': 13, 'Prof-school': 14, 'Some-college': 15}
features marital-status
mapping {'Divorced': 0, 'Married-AF-spouse': 1, 'Married-civ-spouse': 2, 'Married-spouse-absent': 3, 'Never-married': 4, 'Separated': 5, 'Widowed': 6}
features occupation
mapping {'Adm-clerical': 0, 'Armed-Forces': 1, 'Craft-repair': 2, 'Exec-managerial': 3, 'Farming-fishing': 4, 'Handlers-cleaners': 5, 'Machine-op-inspct': 6, 'Other-service': 7, 'Priv-house-serv': 8, 'Prof-specialty': 9, 'Protective-serv': 10, 'Sales': 11, 'Tech-support': 12, 'Transport-moving': 13}
features relationship
mapping {'Husband': 0, 'Not-in-family': 1, 'Ot

In [14]:
x = a.values[:,0:-1]
y = a.values[:,-1]

In [15]:
print(x.shape,y.shape)

(27414, 14) (27414,)


In [16]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train,  y_test = train_test_split(x,y,test_size=0.3, random_state=10)

In [17]:
print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)

(19189, 14)
(19189,)
(8225, 14)
(8225,)


In [ ]:
classifier = LogisticRegression()

#performing kfold_cross_validation
from sklearn.model_selection import KFold
kfold_cv = KFold(n_splits=10,shuffle=True)
#print(kfold_cv)

from sklearn.model_selection import cross_val_score
#running the model using scoring metric as accuracy 
kfold_cv_result = cross_val_score(estimator=classifier,x = x_train, y = y_train, cv = kfold_cv)

print(kfold_cv_result)

#finiding the mean 
print(kfold_cv_result.mean())
#for the sake of evaluation the model is it derable or not

In [18]:
from sklearn.linear_model import LogisticRegression

#create a model object
classifier = LogisticRegression()

#train the model object
model = classifier.fit(x_train,y_train)

c:\Users\pchor\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


Adjusting the threshold

In [ ]:
#store the predicted probabilities
y_pred_prob = model.predict_proba(x_test)
print(y_pred_prob)

In [ ]:
# y_pred = classifier.predict(x_test)
# print(y_pred)
# print(list(zip(y_test,y_pred)))

y_pred_class = []

for value in y_pre_prob[:.1]:
    if value > 0.4:
        y_pred_class.append(1)
    else:
        y_pred_class.append(0)
print(y_pred_class)

[1 1 1 ... 1 1 0]
[(1, 1), (1, 1), (1, 1), (1, 1), (1, 1), (1, 1), (0, 0), (0, 0), (1, 1), (1, 1), (1, 0), (0, 0), (0, 1), (0, 0), (0, 0), (0, 0), (0, 0), (1, 0), (1, 1), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 1), (1, 0), (0, 0), (1, 1), (1, 1), (0, 0), (0, 0), (0, 0), (0, 0), (1, 0), (1, 0), (0, 1), (1, 0), (1, 0), (1, 0), (0, 0), (1, 0), (1, 0), (1, 0), (0, 0), (0, 0), (0, 0), (1, 1), (1, 0), (0, 0), (0, 1), (0, 0), (1, 0), (0, 1), (0, 0), (1, 0), (1, 0), (0, 0), (0, 0), (0, 1), (1, 0), (1, 1), (1, 1), (0, 0), (0, 0), (1, 1), (1, 1), (0, 1), (0, 0), (1, 1), (1, 0), (0, 0), (0, 1), (1, 1), (0, 0), (0, 1), (0, 0), (0, 1), (0, 0), (1, 0), (1, 0), (0, 0), (0, 0), (1, 1), (1, 1), (0, 0), (0, 0), (0, 1), (1, 0), (0, 0), (0, 0), (1, 1), (0, 1), (0, 1), (1, 0), (1, 1), (1, 0), (1, 0), (1, 1), (0, 0), (0, 0), (0, 0), (0, 1), (1, 1), (1, 0), (0, 0), (1, 1), (0, 1), (1, 0), (0, 0), (0, 0), (0, 0), (1, 1), (0, 0), (1, 1), (0, 0), (0, 0), (1, 0), (0, 0), (1, 1), (0, 0), (0, 0), (0, 0), (0, 0

In [20]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
cfm = confusion_matrix(y_test,y_pred)
print(cfm)

print("Classification report:")

print(classification_report(y_test,y_pred))

acc = accuracy_score(y_test,y_pred)
print("Accuracy of the Model: ",acc)

[[3941  766]
 [1807 1711]]
Classification report:
              precision    recall  f1-score   support

           0       0.69      0.84      0.75      4707
           1       0.69      0.49      0.57      3518

    accuracy                           0.69      8225
   macro avg       0.69      0.66      0.66      8225
weighted avg       0.69      0.69      0.68      8225

Accuracy of the Model:  0.6871732522796352


In [21]:
import pickle

with open("model.pkl","wb") as p:
    pickle.dump(model,p)

In [22]:
a.head()

,age,workclass,fnlwgt,education,educational-num,marital-status,occupation,relationship,race,gender,capital-gain,capital-loss,hours-per-week,native-country,income
0,28,1,336951,7,12,2,10,0,4,1,0,0,40,38,1
1,44,3,160323,15,10,2,6,0,2,1,7688,0,40,38,1
2,63,5,104626,14,15,2,9,0,4,1,3103,0,32,38,1
3,65,3,184454,11,9,2,6,0,4,1,6418,0,40,38,1
4,48,3,279724,11,9,2,6,0,4,1,3103,0,48,38,1
